[package]
name = "jj"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "0.3"
rusoto_ec2 = "*"
rusoto_signature = "*"
skim = "*"
tokio = "*"
tokio-util = "*"
